apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ajktown-ingress
  namespace: ajktown
  labels:
    app: my-app
spec:
  defaultBackend:
    service:
      name: ajktown-api-svc
      port:
        number: 80
  rules:
    - host: wordnote.ajktown.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ajktown-wordnote-svc
                port:
                  number: 80
    - host: api.ajktown.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ajktown-api-svc
                port:
                  number: 80
    - host: testfe.ajktown.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ajktown-wordnote-svc
                port:
                  number: 80
    - host: testapi.ajktown.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ajktown-api-svc
                port:
                  number: 80
    - host: www.ajktown.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ajktown-api-svc
                port:
                  number: 80
